/** Compact rows: [name, category, docsUrl, auth, exampleEndpoint, ...tags] */
export const EXTRA_APIS = [
  ["Cat Facts", "Animals", "https://alexwohlbruck.github.io/catfacts/", "none", "https://catfact.ninja/facts?limit=10&max_length=140", "fun", "science"],
  ["Dog API", "Animals", "https://dog.ceo/dog-api/", "none", "https://dog.ceo/api/breed/hound/images", "fun", "media"],
  ["Shibe.Online", "Animals", "http://shibe.online/", "none", "https://shibe.online/api/shibes?count=10&urls=true", "fun", "media"],
  ["Axolotl API", "Animals", "https://theaxolotlapi.netlify.app/", "none", "https://theaxolotlapi.netlify.app/api/", "fun", "science"],
  ["AnimeChan", "Anime", "https://animechan.xyz/", "none", "https://animechan.xyz/api/quotes?anime=Naruto", "fun", "media"],
  ["Studio Ghibli", "Anime", "https://ghibliapi.vercel.app/", "none", "https://ghibliapi.vercel.app/films", "fun", "culture"],
  ["Jikan", "Anime", "https://docs.api.jikan.moe/", "none", "https://api.jikan.moe/v4/top/anime", "fun", "ranking"],
  ["NHTSA", "Vehicle", "https://vpic.nhtsa.dot.gov/api/", "none", "https://vpic.nhtsa.dot.gov/api/vehicles/GetMakesForVehicleType/car?format=json", "search", "comparison"],
  ["Rijksmuseum", "Art", "https://data.rijksmuseum.nl/", "none", "https://www.rijksmuseum.nl/api/nl/collection?key=0&format=json&ps=5", "culture", "gallery"],
  ["Harvard Art Museums", "Art", "https://github.com/harvardartmuseums/api-docs", "free-key", "https://api.harvardartmuseums.org/object?size=5&apikey=DEMO_KEY", "culture", "gallery"],
  ["Smithsonian", "Art", "https://edan.si.edu/openaccess/apidocs/", "none", "https://api.si.edu/openaccess/api/v1.0/search?q=cat&api_key=0", "culture", "search"],
  ["Europeana", "Art", "https://pro.europeana.eu/page/apis", "none", "https://api.europeana.eu/record/v2/search.json?wskey=apidemo&query=van%20gogh", "culture", "search"],
  ["Deezer", "Music", "https://developers.deezer.com/api", "none", "https://api.deezer.com/chart/0/tracks", "media", "trending"],
  ["MusicBrainz", "Music", "https://musicbrainz.org/doc/MusicBrainz_API", "none", "https://musicbrainz.org/ws/2/artist/?query=beatles&fmt=json", "search", "education"],
  ["Lyrics.ovh", "Music", "https://lyricsovh.docs.apiary.io/", "none", "https://api.lyrics.ovh/v1/artist/rem/search", "media", "search"],
  ["Open Trivia DB", "Games", "https://opentdb.com/api_config.php", "none", "https://opentdb.com/api.php?amount=5", "fun", "collections"],
  ["Free Chess", "Games", "https://chess-api.com/", "none", "https://chess-api.com/v1", "fun", "tools"],
  ["TCGdex", "Games", "https://www.tcgdex.net/", "none", "https://api.tcgdex.net/v2/en/cards?limit=5", "fun", "collections"],
  ["Marvel", "Games", "https://developer.marvel.com/", "free-key", "https://gateway.marvel.com/v1/public/comics?apikey=DEMO", "fun", "media"],
  ["SWAPI", "Film", "https://swapi.dev/", "none", "https://swapi.dev/api/people", "fun", "education"],
  ["STAPI", "Film", "https://stapi.co/", "none", "https://stapi.co/api/v1/rest/character/search?pageSize=5", "fun", "search"],
  ["TVMaze", "Entertainment", "https://www.tvmaze.com/api", "none", "https://api.tvmaze.com/shows?page=0", "media", "search"],
  ["OMDb", "Entertainment", "https://www.omdbapi.com/", "free-key", "https://www.omdbapi.com/?t=inception&apikey=demo", "media", "search"],
  ["Chronicling America", "News", "https://chroniclingamerica.loc.gov/about/api/", "none", "https://chroniclingamerica.loc.gov/suggest/titles/?q=chicago", "culture", "search"],
  ["GNews", "News", "https://gnews.io/", "free-key", "https://gnews.io/api/v4/top-headlines?category=technology&max=5&apikey=demo", "trending", "social"],
  ["Spaceflight News", "Science", "https://spaceflightnewsapi.net/", "none", "https://api.spaceflightnewsapi.net/v4/articles/?limit=5", "science", "trending"],
  ["Launch Library 2", "Science", "https://thespacedevs.com/llapi", "none", "https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit=5", "science", "time-series"],
  ["Exoplanet Archive", "Science", "https://exoplanetarchive.ipac.caltech.edu/docs/TAP/usingTAP.html", "none", "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+top+5+pl_name+from+ps&format=json", "science", "search"],
  ["Numbers API", "Science", "http://numbersapi.com/", "none", "http://numbersapi.com/42", "fun", "education"],
  ["USGS Water Services", "Science", "https://waterservices.usgs.gov/", "none", "https://waterservices.usgs.gov/nwis/iv/?format=json&sites=01646500&parameterCd=00060", "science", "time-series"],
  ["NOAA Tides", "Weather", "https://api.tidesandcurrents.noaa.gov/api/", "none", "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?date=today&station=9414290&product=predictions&datum=MLLW&time_zone=gmt&units=english&interval=h&format=json", "geo", "time-series"],
  ["WeatherAPI", "Weather", "https://www.weatherapi.com/docs/", "free-key", "https://api.weatherapi.com/v1/current.json?key=demo&q=London", "geo", "real-time"],
  ["7Timer!", "Weather", "http://www.7timer.info/doc.php", "none", "http://www.7timer.info/bin/api.pl?lon=113.17&lat=23.09&product=civilo&output=json", "geo", "time-series"],
  ["Open AQ", "Environment", "https://docs.openaq.org/", "none", "https://api.openaq.org/v2/latest?limit=5", "science", "maps"],
  ["AirVisual", "Environment", "https://www.iqair.com/air-pollution-data-api", "free-key", "https://api.airvisual.com/v2/nearest_city?lat=40.71&lon=-74.00&key=demo", "health", "geo"],
  ["Carbon Interface", "Environment", "https://docs.carboninterface.com/", "free-key", "https://www.carboninterface.com/api/v1/estimates", "science", "tools"],
  ["Climatiq", "Environment", "https://www.climatiq.io/docs", "free-key", "https://api.climatiq.io/data/v1/search?query=electricity", "science", "search"],
  ["OpenStreetMap Nominatim", "Geocoding", "https://nominatim.org/release-docs/develop/api/Overview/", "none", "https://nominatim.openstreetmap.org/search?q=berlin&format=json&limit=5", "geo", "maps"],
  ["GeoNames", "Geocoding", "https://www.geonames.org/export/web-services.html", "free-key", "http://api.geonames.org/searchJSON?q=london&maxRows=5&username=demo", "geo", "search"],
  ["REST Countries v1", "Geography", "https://restcountries.com/", "none", "https://restcountries.com/v3.1/name/france", "geo", "education"],
  ["World Bank", "Government", "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392", "none", "https://api.worldbank.org/v2/country/all/indicator/SI.POV.DDAY?format=json&per_page=5", "comparison", "charts"],
  ["data.gov CKAN", "Government", "https://data.gov/developers/apis", "none", "https://catalog.data.gov/api/3/action/package_search?q=health&rows=5", "search", "education"],
  ["FBI Wanted", "Government", "https://www.fbi.gov/wanted/api", "none", "https://api.fbi.gov/wanted/v1/list", "search", "alerts"],
  ["UK Police", "Government", "https://data.police.uk/docs/", "none", "https://data.police.uk/api/crimes-street/all-crime?lat=52.6297&lng=-1.1312&date=2024-01", "geo", "maps"],
  ["OpenSanctions", "Government", "https://www.opensanctions.org/docs/api/", "none", "https://api.opensanctions.org/search/default?q=smith&limit=5", "search", "alerts"],
  ["Congress.gov", "Government", "https://api.congress.gov/", "free-key", "https://api.congress.gov/v3/bill?api_key=DEMO_KEY&limit=5", "education", "search"],
  ["Pendleton", "Government", "https://www.census.gov/data/developers/data-sets.html", "free-key", "https://api.census.gov/data/timeseries/poverty/saipe?get=NAME,SAEPOVRTALL_PT&for=state:*", "geo", "charts"],
  ["OpenCorporates", "Business", "https://api.opencorporates.com/", "free-key", "https://api.opencorporates.com/companies/search?q=stripe", "search", "comparison"],
  ["Companies House UK", "Business", "https://developer.company-information.service.gov.uk/", "free-key", "https://api.company-information.service.gov.uk/search/companies?q=design", "search", "comparison"],
  ["Frankfurter", "Finance", "https://www.frankfurter.app/docs/", "none", "https://api.frankfurter.app/latest?from=USD&to=EUR,GBP", "finance", "comparison"],
  ["ExchangeRate-API", "Finance", "https://www.exchangerate-api.com/docs", "free-key", "https://v6.exchangerate-api.com/v6/demo/latest/USD", "finance", "real-time"],
  ["Alpha Vantage", "Finance", "https://www.alphavantage.co/documentation/", "free-key", "https://www.alphavantage.co/query?function=TOP_GAINERS_LOSERS&apikey=demo", "finance", "trending"],
  ["FRED", "Finance", "https://fred.stlouisfed.org/docs/api/fred/", "free-key", "https://api.stlouisfed.org/fred/series/observations?series_id=GNPCA&api_key=demo&file_type=json", "finance", "time-series"],
  ["IEX Cloud", "Finance", "https://iexcloud.io/docs/api/", "free-key", "https://cloud.iexapis.com/stable/stock/market/list/gainers?token=demo", "finance", "ranking"],
  ["Binance Public", "Cryptocurrency", "https://binance-docs.github.io/apidocs/spot/en/", "none", "https://api.binance.com/api/v3/ticker/24hr?symbols=%5B%22BTCUSDT%22%2C%22ETHUSDT%22%2C%22BNBUSDT%22%2C%22SOLUSDT%22%2C%22ADAUSDT%22%5D", "finance", "real-time"],
  ["CoinCap", "Cryptocurrency", "https://docs.coincap.io/", "none", "https://api.coincap.io/v2/assets?limit=5", "finance", "trending"],
  ["Blockchair", "Blockchain", "https://blockchair.com/api/docs", "none", "https://api.blockchair.com/bitcoin/stats", "finance", "science"],
  ["Etherscan", "Blockchain", "https://docs.etherscan.io/", "free-key", "https://api.etherscan.io/api?module=stats&action=ethprice&apikey=demo", "finance", "real-time"],
  ["OpenFDA Drugs", "Health", "https://open.fda.gov/apis/drug/", "none", "https://api.fda.gov/drug/label.json?limit=5", "health", "search"],
  ["Disease.sh", "Health", "https://disease.sh/docs/", "none", "https://disease.sh/v3/covid-19/countries?limit=10", "health", "time-series"],
  ["Nutritionix", "Health", "https://developer.nutritionix.com/docs/v2", "free-key", "https://trackapi.nutritionix.com/v2/search/instant?query=apple", "health", "search"],
  ["Open Disease", "Health", "https://disease.sh/", "none", "https://disease.sh/v3/covid-19/historical/all", "health", "charts"],
  ["RxNorm", "Health", "https://lhncbc.nlm.nih.gov/RxNav/APIs/RxNormAPIs.html", "none", "https://rxnav.nlm.nih.gov/REST/drugs.json?name=aspirin", "health", "search"],
  ["Basketball Data", "Sports", "https://www.balldontlie.io/", "none", "https://api.balldontlie.io/v1/players?per_page=5", "fun", "ranking"],
  ["TheSportsDB", "Sports", "https://www.thesportsdb.com/api.php", "free-key", "https://www.thesportsdb.com/api/v1/json/3/searchteams.php?t=Arsenal", "fun", "search"],
  ["Football-Data.org", "Sports", "https://www.football-data.org/documentation/quickstart", "free-key", "https://api.football-data.org/v4/competitions", "fun", "comparison"],
  ["OpenLigaDB", "Sports", "https://api.openligadb.de/", "none", "https://api.openligadb.de/getmatchdata/bl1/2023", "fun", "time-series"],
  ["Strava", "Sports", "https://developers.strava.com/", "free-key", "https://www.strava.com/api/v3/segments/explore?bounds=37.0,-122.5,37.5,-122.0", "geo", "maps"],
  ["Transport for London", "Transportation", "https://api.tfl.gov.uk/", "free-key", "https://api.tfl.gov.uk/Line/Mode/tube/Status", "transit", "real-time"],
  ["MBTA", "Transportation", "https://www.mbta.com/developers/v3-api", "none", "https://api-v3.mbta.com/routes?filter[type]=0,1", "transit", "geo"],
  ["BART", "Transportation", "https://api.bart.gov/docs/overview/index.aspx", "free-key", "https://api.bart.gov/api/bsa.aspx?cmd=bsa&key=DEMO", "transit", "alerts"],
  ["TransitLand", "Transportation", "https://www.transit.land/documentation/", "none", "https://transit.land/api/v2/rest/feeds?per_page=5", "transit", "geo"],
  ["Aviationstack", "Transportation", "https://aviationstack.com/documentation", "free-key", "http://api.aviationstack.com/v1/flights?access_key=demo&limit=5", "transit", "real-time"],
  ["OpenSky Network", "Transportation", "https://openskynetwork.github.io/opensky-api/", "none", "https://opensky-network.org/api/states/all", "transit", "real-time"],
  ["USGS Elevation", "Geography", "https://www.usgs.gov/centers/eros/science/3dep", "none", "https://nationalmap.gov/epqs/pqs.php?x=-105&y=40&units=Meters&output=json", "geo", "science"],
  ["NASA APOD", "Science", "https://api.nasa.gov/", "free-key", "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&count=5", "science", "media"],
  ["NASA NeoWs", "Science", "https://api.nasa.gov/", "free-key", "https://api.nasa.gov/neo/rest/v1/neo/browse?api_key=DEMO_KEY", "science", "alerts"],
  ["Inspire", "Science", "https://inspirehep.net/", "none", "https://inspirehep.net/api/literature?q=quantum&size=5", "science", "search"],
  ["CrossRef", "Science", "https://api.crossref.org/", "none", "https://api.crossref.org/works?query=machine+learning&rows=5", "science", "search"],
  ["OpenAlex", "Science", "https://docs.openalex.org/", "none", "https://api.openalex.org/works?search=climate&per_page=5", "science", "search"],
  ["PubMed", "Health", "https://www.ncbi.nlm.nih.gov/home/develop/api/", "none", "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=coffee&retmode=json", "health", "search"],
  ["ClinicalTrials.gov", "Health", "https://clinicaltrials.gov/data-api/api", "none", "https://clinicaltrials.gov/api/v2/studies?query.cond=cancer&pageSize=5", "health", "search"],
  ["Open Targets", "Health", "https://platform-docs.opentargets.org/", "none", "https://api.platform.opentargets.org/api/v4/graphql", "health", "science"],
  ["GBIF Species", "Science", "https://www.gbif.org/developer/species", "none", "https://api.gbif.org/v1/species/search?q=ursus&limit=5", "science", "search"],
  ["iNaturalist", "Science", "https://api.inaturalist.org/v1/docs/", "none", "https://api.inaturalist.org/v1/observations?per_page=5&order=desc&order_by=created_at", "science", "geo"],
  ["EOL", "Science", "https://eol.org/docs/what-is-eol/data-services", "none", "https://v3.globiz.org/parasite-galaxy/api/taxon/search?q=canis", "science", "education"],
  ["PlantNet", "Science", "https://my.plantnet.org/", "free-key", "https://my-api.plantnet.org/v2/projects", "science", "search"],
  ["Open Topo Data", "Geography", "https://www.opentopodata.org/", "none", "https://api.opentopodata.org/v1/aster30m?locations=40.7128,-74.0060|34.0522,-118.2437|51.5074,-0.1278|48.8566,2.3522|35.6762,139.6503", "geo", "maps"],
  ["Sunrise Sunset", "Weather", "https://sunrise-sunset.org/api", "none", "https://api.sunrise-sunset.org/json?lat=36.7201&lng=-4.4203", "geo", "time-series"],
  ["IP Geolocation", "Geocoding", "https://ip-api.com/docs", "none", "http://ip-api.com/json/8.8.8.8", "geo", "tools"],
  ["Zippopotam", "Geography", "https://www.zippopotam.us/", "none", "https://api.zippopotam.us/us/90210", "geo", "education"],
  ["Rest Countries Flags", "Geography", "https://flagcdn.com/", "none", "https://flagcdn.com/en/codes.json", "media", "education"],
  ["Universities List", "Education", "http://universities.hipolabs.com/", "none", "http://universities.hipolabs.com/search?country=United+States", "education", "search"],
  ["Open Library Authors", "Books", "https://openlibrary.org/developers/api", "none", "https://openlibrary.org/search/authors.json?q=twain&limit=10", "education", "search"],
  ["Google Books", "Books", "https://developers.google.com/books", "free-key", "https://www.googleapis.com/books/v1/volumes?q=design&maxResults=5&key=demo", "search", "media"],
  ["PoetryDB", "Books", "https://github.com/thundercomb/poetrydb", "none", "https://poetrydb.org/author/Emily%20Dickinson", "culture", "search"],
  ["Quotable", "Social", "https://dummyjson.com/docs/quotes", "none", "https://dummyjson.com/quotes?limit=10", "fun", "media"],
  ["Advice Slip", "Social", "https://api.adviceslip.com/", "none", "https://api.adviceslip.com/advice/search?query=life", "fun", "media"],
  ["Bored API", "Social", "https://www.boredapi.com/", "none", "https://www.boredapi.com/api/activity", "fun", "tools"],
  ["Random User", "Social", "https://randomuser.me/documentation", "none", "https://randomuser.me/api/?results=5", "tools", "fun"],
  ["JSONPlaceholder", "Development", "https://jsonplaceholder.typicode.com/", "none", "https://jsonplaceholder.typicode.com/posts", "tools", "education"],
  ["HTTPBin", "Development", "https://httpbin.org/", "none", "https://httpbin.org/uuid?count=10", "tools", "education"],
  ["ReqRes", "Development", "https://reqres.in/", "none", "https://reqres.in/api/users?page=1", "tools", "education"],
  ["GitHub Public", "Development", "https://docs.github.com/en/rest", "none", "https://api.github.com/repos/github/gitignore", "social", "ranking"],
  ["GitLab Public", "Development", "https://docs.gitlab.com/ee/api/", "none", "https://gitlab.com/api/v4/projects?visibility=public&per_page=5", "social", "search"],
  ["npm Registry", "Development", "https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md", "none", "https://registry.npmjs.org/-/v1/search?text=react&size=10", "tools", "search"],
  ["PyPI", "Development", "https://warehouse.pypa.io/api-reference/", "none", "https://pypi.org/search/?q=flask&format=json", "tools", "search"],
  ["StackExchange", "Social", "https://api.stackexchange.com/docs", "none", "https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&site=stackoverflow&pagesize=5", "social", "ranking"],
  ["Reddit", "Social", "https://www.reddit.com/dev/api/", "none", "https://www.reddit.com/r/dataisbeautiful/top.json?limit=5", "social", "trending"],
  ["Dev.to", "Social", "https://developers.forem.com/api", "none", "https://dev.to/api/articles?per_page=5", "social", "trending"],
  ["Mastodon", "Social", "https://docs.joinmastodon.org/api/", "none", "https://mastodon.social/api/v1/trends/tags", "social", "trending"],
  ["Lobste.rs", "Social", "https://lobste.rs/", "none", "https://lobste.rs/hottest.json", "social", "ranking"],
  ["Product Hunt", "Business", "https://api.producthunt.com/v2/docs", "free-key", "https://api.producthunt.com/v2/api/graphql", "trending", "ranking"],
  ["Y Combinator", "Business", "https://github.com/yc-oss/api", "none", "https://yc-oss.github.io/api/meta.json", "trending", "education"],
  ["OpenML", "Machine Learning", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/data/list/limit/5", "science", "search"],
  ["Hugging Face", "Machine Learning", "https://huggingface.co/docs/hub/api", "none", "https://huggingface.co/api/models?limit=5", "science", "search"],
  ["OpenML Datasets", "Data", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/data/list/limit/5", "science", "education"],
  ["Kaggle Public", "Data", "https://www.kaggle.com/docs/api", "free-key", "https://www.kaggle.com/api/v1/datasets/list?pageSize=5", "science", "search"],
  ["Wikidata SPARQL", "Knowledge", "https://query.wikidata.org/", "none", "https://query.wikidata.org/sparql?query=SELECT%20?item%20WHERE%20{?item%20wdt:P31%20wd:Q5}%20LIMIT%205", "graphs", "search"],
  ["Wikipedia", "Knowledge", "https://www.mediawiki.org/wiki/API:Main_page", "none", "https://en.wikipedia.org/api/rest_v1/page/summary/Open_data", "education", "search"],
  ["Dictionary API", "Text", "https://dictionaryapi.dev/", "none", "https://api.dictionaryapi.dev/api/v2/entries/en/prototype", "education", "tools"],
  ["Datamuse", "Text", "https://www.datamuse.com/api/", "none", "https://api.datamuse.com/words?ml=spoon&max=5", "tools", "search"],
  ["Wordnik", "Text", "https://developer.wordnik.com/", "free-key", "https://api.wordnik.com/v4/word.json/randomWords?limit=5&api_key=demo", "education", "fun"],
  ["Pexels", "Photography", "https://www.pexels.com/api/", "free-key", "https://api.pexels.com/v1/search?query=nature&per_page=5", "media", "gallery"],
  ["Unsplash", "Photography", "https://unsplash.com/developers", "free-key", "https://api.unsplash.com/photos?per_page=5&client_id=demo", "media", "gallery"],
  ["Giphy", "Entertainment", "https://developers.giphy.com/docs/", "free-key", "https://api.giphy.com/v1/gifs/trending?api_key=demo&limit=5", "fun", "media"],
  ["Tenor", "Entertainment", "https://tenor.com/gifapi/documentation", "free-key", "https://tenor.googleapis.com/v2/featured?key=demo&limit=5", "fun", "media"],
  ["Colorado Data", "Government", "https://data.colorado.gov/", "none", "https://data.colorado.gov/resource.json", "geo", "search"],
  ["NYC Open Data", "Government", "https://opendata.cityofnewyork.us/", "none", "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=5", "geo", "search"],
  ["SF Open Data", "Government", "https://datasf.org/opendata/", "none", "https://data.sfgov.org/resource/i98e-djp9.json?$limit=5", "geo", "local"],
  ["Chicago Data", "Government", "https://data.cityofchicago.org/", "none", "https://data.cityofchicago.org/resource/ijpz-cqmj.json?$limit=5", "geo", "local"],
  ["UK Food Hygiene", "Food", "https://api.ratings.food.gov.uk/", "none", "https://api.ratings.food.gov.uk/Establishments?limit=5", "health", "local"],
  ["USDA FoodData", "Food", "https://fdc.nal.usda.gov/api-guide.html", "free-key", "https://api.nal.usda.gov/fdc/v1/foods/search?query=apple&pageSize=5&api_key=DEMO_KEY", "health", "search"],
  ["MealDB", "Food", "https://www.themealdb.com/api.php", "free-key", "https://www.themealdb.com/api/json/v1/1/search.php?s=Arrabiata", "fun", "local"],
  ["Punk API", "Food", "https://punkapi.com/documentation", "none", "https://punkapi.com/v2/beers?per_page=5", "fun", "local"],
  ["Open Brewery", "Food", "https://www.openbrewerydb.org/documentation", "none", "https://api.openbrewerydb.org/v1/breweries?per_page=5", "local", "geo"],
  ["Spoonacular", "Food", "https://spoonacular.com/food-api/docs", "free-key", "https://api.spoonacular.com/recipes/complexSearch?number=5&apiKey=demo", "health", "search"],
  ["Edamam", "Food", "https://developer.edamam.com/", "free-key", "https://api.edamam.com/api/recipes/v2?type=public&q=salad&app_id=demo&app_key=demo", "health", "search"],
  ["Open Notify People", "Space", "http://open-notify.org/", "none", "http://api.open-notify.org/astros.json", "science", "real-time"],
  ["SpaceX API", "Science", "https://github.com/r-spacex/SpaceX-API", "none", "https://api.spacexdata.com/v4/launches?limit=10", "science", "time-series"],
  ["Launch Library", "Science", "https://thespacedevs.com/llapi", "none", "https://ll.thespacedevs.com/2.2.0/config/launchpad/?limit=5", "science", "search"],
  ["Asterank", "Science", "https://www.asterank.com/", "none", "https://www.asterank.com/api/kepler?limit=5", "science", "search"],
  ["USGS Volcano", "Science", "https://volcanoes.usgs.gov/", "none", "https://volcano.status.gov/widget/v1/widget.json", "science", "alerts"],
  ["OpenAQ Countries", "Environment", "https://docs.openaq.org/", "none", "https://api.openaq.org/v2/countries?limit=10", "geo", "comparison"],
  ["Purple Air", "Environment", "https://api.purpleair.com/", "free-key", "https://api.purpleair.com/v1/sensors?fields=sensor_index,name&max_age=3600", "health", "maps"],
  ["OpenCellID", "Geography", "https://opencellid.org/", "free-key", "https://opencellid.org/cell/getInArea?key=demo", "geo", "maps"],
  ["Rest Countries Region", "Geography", "https://restcountries.com/", "none", "https://restcountries.com/v3.1/region/africa?fields=name,population", "comparison", "geo"],
  ["GeoJS", "Geocoding", "https://www.geojs.io/", "none", "https://get.geojs.io/v1/ip/geo.json", "geo", "tools"],
  ["Rest Countries Currency", "Finance", "https://restcountries.com/", "none", "https://restcountries.com/v3.1/currency/usd", "finance", "education"],
  ["VATComply", "Finance", "https://www.vatcomply.com/documentation", "none", "https://api.vatcomply.com/rates?base=USD", "finance", "comparison"],
  ["CoinDesk", "Cryptocurrency", "https://www.coindesk.com/coindesk-api", "none", "https://api.coindesk.com/v1/bpi/currentprice.json", "finance", "real-time"],
  ["Alternative.me Fear Greed", "Cryptocurrency", "https://alternative.me/crypto/fear-and-greed-index/", "none", "https://api.alternative.me/fng/?limit=5", "finance", "charts"],
  ["OpenML Tasks", "Machine Learning", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/task/list/limit/5", "science", "tools"],
  ["Archive.org", "Books", "https://archive.org/developers/", "none", "https://archive.org/advancedsearch.php?q=collection:opensource&fl[]=identifier&rows=5&output=json", "media", "search"],
  ["Library of Congress", "Books", "https://www.loc.gov/apis/", "none", "https://www.loc.gov/search/?q=maps&fo=json", "culture", "search"],
  ["OpenStreetMap Overpass", "Geography", "https://wiki.openstreetmap.org/wiki/Overpass_API", "none", "https://overpass-api.de/api/interpreter?data=[out:json];node(around:1000,48.858,2.294);out;", "geo", "maps"],
  ["OpenTripPlanner", "Transportation", "https://docs.opentripplanner.org/", "none", "https://demo.opentripplanner.org/otp/routers/default/plan?fromPlace=40.7,-74.0&toPlace=40.8,-73.9", "transit", "geo"],
  ["Open Charge Map", "Transportation", "https://openchargemap.org/site/develop/api", "none", "https://api.openchargemap.io/v3/poi/?output=json&maxresults=5", "transit", "geo"],
  ["Bikeshare Map", "Transportation", "https://gbfs.bcycle.com/", "none", "https://gbfs.bcycle.com/gbfs.json", "transit", "real-time"],
  ["OpenSky Flights", "Transportation", "https://openskynetwork.github.io/opensky-api/", "none", "https://opensky-network.org/api/flights/all?begin=1700000000&end=1700003600", "transit", "time-series"],
  ["OpenML Flows", "Data", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/flow/list/limit/5", "science", "tools"],
  ["OpenML Tasks Type", "Data", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/task/type", "science", "education"],
  ["Open Civic Data", "Government", "https://open-civic-data.readthedocs.io/", "none", "https://open-civic-data.readthedocs.io/", "geo", "education"],
  ["OpenStates", "Government", "https://docs.openstates.org/", "none", "https://v3.openstates.org/bills?jurisdiction=ocd-jurisdiction/country:us/state:ca&per_page=5", "education", "search"],
  ["Ballotpedia", "Government", "https://ballotpedia.org/", "none", "https://ballotpedia.org/", "education", "search"],
  ["OpenFEC", "Government", "https://api.open.fec.gov/developers/", "free-key", "https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&per_page=5", "comparison", "search"],
  ["CourtListener", "Government", "https://www.courtlistener.com/help/api/", "none", "https://www.courtlistener.com/api/rest/v3/opinions/?page_size=5", "search", "education"],
  ["OpenCorporates US", "Business", "https://api.opencorporates.com/", "free-key", "https://api.opencorporates.com/companies/us", "search", "comparison"],
  ["SEC EDGAR", "Finance", "https://www.sec.gov/edgar/sec-api-documentation", "none", "https://data.sec.gov/submissions/CIK0000320193.json", "finance", "search"],
  ["Treasury Fiscal", "Finance", "https://fiscaldata.treasury.gov/api-documentation/", "none", "https://api.fiscaldata.treasury.gov/services/api/v1/accounting/od/rates_of_exchange?sort=-record_date&page[size]=5", "finance", "time-series"],
  ["BLS", "Government", "https://www.bls.gov/developers/", "free-key", "https://api.bls.gov/publicAPI/v2/timeseries/data/", "finance", "time-series"],
  ["OpenML Studies", "Machine Learning", "https://docs.openml.org/", "none", "https://www.openml.org/api/v1/json/study/list/limit/5", "science", "education"],
  ["Agify", "Tools", "https://agify.io/", "none", "https://api.agify.io?name[]=michael&name[]=jessica&name[]=oliver&name[]=sophia&name[]=liam", "tools", "fun"],
  ["Genderize", "Tools", "https://genderize.io/", "none", "https://api.genderize.io?name[]=luc&name[]=emma&name[]=alex&name[]=jordan&name[]=taylor", "tools", "fun"],
  ["Nationalize", "Tools", "https://nationalize.io/", "none", "https://api.nationalize.io?name[]=nathaniel&name[]=yuki&name[]=olga&name[]=carlos&name[]=mei", "geo", "fun"],
  ["IPinfo Lite", "Geocoding", "https://ipinfo.io/developers", "free-key", "https://ipinfo.io/8.8.8.8/json?token=demo", "geo", "tools"],
  ["Abstract Email", "Tools", "https://www.abstractapi.com/email-verification-validation-api", "free-key", "https://emailvalidation.abstractapi.com/v1/?api_key=demo&email=test@example.com", "tools", "search"],
  ["Abstract Phone", "Tools", "https://www.abstractapi.com/phone-validation-api", "free-key", "https://phonevalidation.abstractapi.com/v1/?api_key=demo&phone=+14155552671", "tools", "search"],
  ["UUID Generator", "Tools", "https://www.uuidtools.com/docs", "none", "https://www.uuidtools.com/api/generate/v1/count/5", "tools", "fun"],
  ["Yes No Maybe", "Fun", "https://yesno.wtf/api", "none", "https://yesno.wtf/api", "fun", "media"],
  ["Kanye Rest", "Fun", "https://kanye.rest/", "none", "https://api.kanye.rest/quotes", "fun", "media"],
];
